name: Run Sign-In Suite

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Run TestNG Suite
        run: |
          ./mvnw test -DsuiteXmlFile=01-sign-in-successfull.xml
          # Adjust the command based on your project's build tool

      - name: Debug Information
        run: |
          echo "Current Directory: $(pwd)"
          ls -la
          # Add more debugging commands as needed.
