name: Run Sign-In Suite

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "8"

      - name: Set execute permissions for mvnw
        run: |
          chmod +x mvnw
        working-directory: .  # Set to the root directory

      - name: Run TestNG Suite
        working-directory: .  # Set to the root directory
        run: |
          ./mvnw test -DsuiteXmlFile=testSuites/01-sign-in-successfull.xml
          # Adjust the command based on your project's build tool

      - name: Clear Maven Cache
        run: |
         mvn dependency:purge-local-repository

      - name: Debug Information
        run: |
          echo "Current Directory: $(pwd)"
          echo "Java Version: $(java -version)"
          echo "Maven Version: $(mvn -version)"
          echo "Current Directory: $(pwd)"
          ls -la
          ls -la
          # Add more debugging commands as needed
