on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Set execute permissions for mvnw
        run: |
          chmod +x mvnw
        working-directory: .  # Set to the root directory

      - name: Run TestNG Suite
        working-directory: .  # Set to the root directory
        run: |
          ./mvnw test -DsuiteXmlFile=testSuites/04-Internal_Reoprts.xml -suitename "Admin Sign-in Successfull And Generate Supdt. Inspection And Navigation Audit Report" -verbose
    # Adjust the command based on your project's build tool

      - name: Debug Information
        run: |
          echo "Current Directory: $(pwd)"
          ls -la
          # Add more debugging commands as needed
