name: Run TestNG Suites

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SUITE_1_PATH: $GITHUB_WORKSPACE/testSuites/01-sign-in-successfull.xml
      #SUITE_2_PATH: $GITHUB_WORKSPACE/testSuites/suite2.xml
      # Add more suites as needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "8"

      - name: Set execute permissions for mvnw
        run: |
          chmod +x mvnw
        working-directory: .  # Set to the root directory

      - name: Run TestNG Suites
        working-directory: .  # Set to the root directory
        run: |
          ./mvnw test -Dsurefire.suiteXmlFiles=$SUITE_1_PATH,$SUITE_2_PATH
          # Add more suites using a comma-separated list

      - name: Clear Maven Cache
        run: |
         mvn dependency:purge-local-repository

      - name: Debug Information
        run: |
          echo "Current Directory: $(pwd)"
          echo "Java Version: $(java -version)"
          echo "Maven Version: $(mvn -version)"
          echo "Current Directory: $(pwd)"
          ls -la
